
/*********************************************************************
***                                                                 ***
***  Source code generated by kernel2cu.pl                          ***
***                                                                 ***
***  Please do not edit                                             ***
***                                                                 ***
*********************************************************************/
#include "vglImage.h"
/** vglCudaCopy

    Copy of image in cuda context.
*/
void vglCudaCopy(VglImage* input, VglImage* output);

/** vglCudaInvert

    Inverts image stored in cuda context.
*/
void vglCudaInvert(VglImage* input, VglImage* output);

/** vglCudaInvertOnPlace

    Inverts image, stored in cuda context, on place.
*/
void vglCudaInvertOnPlace(VglImage* input);

